services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: viditk03/medical-bills-backend:latest
    ports:
      - "8000:8000"
    environment:
      # Connect to your server's native Postgres 15 database
      - DATABASE_URL=postgresql://postgres:Password@123@host.docker.internal:5432/matrix
      
      # Connect to external Ollama instance
      - OLLAMA_BASE_URL=http://192.168.112.2:11434
    volumes:
      # Keep raw_storage mounted to host for persistence of uploaded files
      - ./raw_storage:/app/raw_storage

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: viditk03/medical-bills-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
