FROM --platform=linux/amd64 node:20-alpine as build

WORKDIR /app

# Copy dependency files
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy the rest of the frontend code
COPY frontend/ .

# Build the frontend
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN npm run build

# Serve the app with Nginx
FROM --platform=linux/amd64 nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
